services:
  client1:
    build: "./client/"
    ports:
      - 8011:8000
    container_name: client1
    environment:
      - CLIENT_NAME=Client1
      - MY_CA=ca1
    networks:
      - default
  root_ca:
    build: "./root_ca"
    container_name: root_ca
    ports:
      - 8000:8000
    networks:
      - default
  client2:
    build: "./client/"
    ports:
      - 8012:8000
    container_name: client2
    environment:
      - CLIENT_NAME=Client2
      - MY_CA=ca1
    networks:
      - default
  client3:
    build: "./client/"
    ports:
      - 8013:8000
    container_name: client3
    environment:
      - CLIENT_NAME=Client3
      - MY_CA=ca2
    networks:
      - default
  client4:
    build: "./client/"
    ports:
      - 8014:8000
    container_name: client4
    environment:
      - CLIENT_NAME=Client4
      - MY_CA=ca2
    networks:
      - default
    
    
  ca1:
    build: ./ca1
    ports:
      - "8001:8001"
    networks:
      - default

  ca2:
    build: ./ca2
    ports:
      - "8002:8001"
    networks:
      - default